In [1]:
import pandas as pd
from pathlib import Path

In [2]:
from config import config

In [3]:
root = Path("../..")

In [4]:
en_meta_path = root / config.METADATA_DIR / "metadata_en.csv"
bn_meta_path = root / config.METADATA_DIR / "bn/metadata_bn.csv"
en_meta_path.exists(), bn_meta_path.exists() # has to be True

(True, True)

In [5]:
en_meta_df = pd.read_csv(en_meta_path)
bn_meta_df = pd.read_csv(bn_meta_path)

In [6]:
en_meta_df.head()

,audio_file_stem,lyric_file_stem,quadrant,genres
0,MT0009968194,MT0009968194,Q1,Country
1,MT0004506984,MT0004506984,Q1,"Adult Contemporary,R&B,Contemporary Pop/Rock,D..."
2,MT0011358600,MT0011358600,Q4,Blues
3,A168,L168,Q4,"Electronic,Ethnic Fusion,Club/Dance,New Age"
4,MT0009239443,MT0009239443,Q2,"International,Pop/Rock"

In [7]:
bn_meta_df.head()

,id,sentence,genre
0,-ph4mykFp9I_seg_00005,সাগরে মানুষের হৃদয় ভরে ওঠে আবার শূন্য হবার জন...,Alternative
1,ECh1rS2ipJw_seg_00003,বাজিয়ে আমার মনের মত দিও সাজিয়ে আমি বড় অসহায...,Rock
2,KdURvuVydnI_seg_00001,আমি নিতে দেবো না সময়কে এক মুঠো ভরা যোচনা যাই ...,Alternative
3,mli5roiIW-s_seg_00010,সকাল আয় ঘুম চুম বন্দে তার সারা কপালে যাতে ঘুম...,Indie/Folk-Pop
4,nPmCDRMwvaA_seg_00004,দেহের বাইরে প্রেম আমার সত্য আত্মা কঠিন কঠিন সব...,Rock

In [8]:
en_meta_df["language"] = "en"
en_meta_df["label"] = 0
bn_meta_df["language"] = "bn"
bn_meta_df["label"] = 1
bn_meta_df.rename(columns={"id": "audio_file_stem"}, inplace=True)
en_meta_df.rename(columns={"genres": "genre"}, inplace=True)

In [9]:
en_meta_df

,audio_file_stem,lyric_file_stem,quadrant,genre,language,label
0,MT0009968194,MT0009968194,Q1,Country,en,0
1,MT0004506984,MT0004506984,Q1,"Adult Contemporary,R&B,Contemporary Pop/Rock,D...",en,0
2,MT0011358600,MT0011358600,Q4,Blues,en,0
3,A168,L168,Q4,"Electronic,Ethnic Fusion,Club/Dance,New Age",en,0
4,MT0009239443,MT0009239443,Q2,"International,Pop/Rock",en,0
...,...,...,...,...,...,...
120,MT0013350034,MT0013350034,Q1,"Stage & Screen,Vocal",en,0
121,MT0001889244,MT0001889244,Q1,"Electronic,Pop/Rock,R&B",en,0
122,MT0007349422,MT0007349422,Q2,Rap,en,0
123,MT0001511433,MT0001511433,Q4,"Country,Holiday",en,0
124,MT0000734482,MT0000734482,Q4,Electronic,en,0

In [10]:
bn_meta_df

,audio_file_stem,sentence,genre,language,label
0,-ph4mykFp9I_seg_00005,সাগরে মানুষের হৃদয় ভরে ওঠে আবার শূন্য হবার জন...,Alternative,bn,1
1,ECh1rS2ipJw_seg_00003,বাজিয়ে আমার মনের মত দিও সাজিয়ে আমি বড় অসহায...,Rock,bn,1
2,KdURvuVydnI_seg_00001,আমি নিতে দেবো না সময়কে এক মুঠো ভরা যোচনা যাই ...,Alternative,bn,1
3,mli5roiIW-s_seg_00010,সকাল আয় ঘুম চুম বন্দে তার সারা কপালে যাতে ঘুম...,Indie/Folk-Pop,bn,1
4,nPmCDRMwvaA_seg_00004,দেহের বাইরে প্রেম আমার সত্য আত্মা কঠিন কঠিন সব...,Rock,bn,1
...,...,...,...,...,...
120,CKfhGvUPXkY_seg_00005,আধারে মিলিয়ে আমার স্বপ্ন আমার সাথে যেন স্বপ্ন...,Rock,bn,1
121,G8SKzENt8Is_seg_00003,ভিজিয়ে তুমিও কি আমার সাথে পথে হাত চড়িয়ে কদম,Indie/Folk-Pop,bn,1
122,KWEHAN37n_w_seg_00009,কিনা বিরহ নিলে নিলে বাঁধে বাসা অজানা ব্যথা অধর...,Pop,bn,1
123,jw5Ob3TXCho_seg_00007,স্মৃতিগুলো মুছে যায় অচেনা কুয়া সাথে সময়ে যে...,Pop,bn,1
124,qpfyAc2J1JE_seg_00003,ওপারে আমি জানি তুমিও পারো তার হাসিটা ফোটাতে তু...,Pop,bn,1

In [11]:
bn_meta_df[bn_meta_df["audio_file_stem"] == "-Bfa-aVa7MU_seg_00002"]

,audio_file_stem,sentence,genre,language,label
89,-Bfa-aVa7MU_seg_00002,দূরু তোমার উতাস চুলের ভাজে মৃদু যোছনা মাখা গন্ধ,Rock,bn,1

In [12]:
combined_meta_df = pd.concat([en_meta_df[["audio_file_stem", "language", "label", "genre"]], bn_meta_df[["audio_file_stem", "language", "label", "genre"]]], axis=0)
combined_meta_df.reset_index(drop=True, inplace=True)

In [13]:
combined_meta_df

,audio_file_stem,language,label,genre
0,MT0009968194,en,0,Country
1,MT0004506984,en,0,"Adult Contemporary,R&B,Contemporary Pop/Rock,D..."
2,MT0011358600,en,0,Blues
3,A168,en,0,"Electronic,Ethnic Fusion,Club/Dance,New Age"
4,MT0009239443,en,0,"International,Pop/Rock"
...,...,...,...,...
245,CKfhGvUPXkY_seg_00005,bn,1,Rock
246,G8SKzENt8Is_seg_00003,bn,1,Indie/Folk-Pop
247,KWEHAN37n_w_seg_00009,bn,1,Pop
248,jw5Ob3TXCho_seg_00007,bn,1,Pop
249,qpfyAc2J1JE_seg_00003,bn,1,Pop

In [14]:
DEST_PATH = root / config.METADATA_DIR / "metadata_en_bn.csv"
combined_meta_df.to_csv(DEST_PATH, index=False)